# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-20 12:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginreg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='newuser',
        ),
    ]
